# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-29 02:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 29, 2, 49, 12, 851000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 29, 2, 49, 12, 851000, tzinfo=utc)),
        ),
    ]
