# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-10 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2016, 11, 10)),
        ),
    ]
