# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-02 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0002_auto_20161128_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 2, 19, 14, 35, 234000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 2, 19, 14, 35, 234000, tzinfo=utc)),
        ),
    ]
