# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 18:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0005_auto_20161115_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 12, 20, 32, 290000)),
        ),
        migrations.AddField(
            model_name='profession',
            name='jobs',
            field=models.ManyToManyField(to='dispatcher.Jobs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='jobs',
            field=models.ManyToManyField(to='dispatcher.Jobs'),
        ),
    ]
