# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0008_auto_20161117_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='dispatcher.Job'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='dispatcher.Job'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 12, 33, 42, 877000)),
        ),
    ]
